baseurl: "http://localhost:1313/"
languageCode: "cs-cz"
title: "Draken Brno"
theme: "draken-hugo"
canonifyurls: false;


menu:
  main:
    - identifier: 'radost-na-drakenu'
      name: "Radost na Drakenu"
      url: "http://radost-na-drakenu.webnode.cz/"
      parent: aktivity
      weight: 400
    - identifier: 'squash-rezervace'
      name: "Rezervace"
      parent: squash
      weight: 100
      url: http://squash-draken.isportsystem.cz/


params:
  sidebar: "left"
