---
baseurl: http://localhost:1313/
languageCode: cs-cz
title: Draken Brno
theme: draken-hugo
canonifyurls: false;
menu:
  main:
  - identifier: squash-rezervace
    name: Rezervace
    parent: squash
    url: http://squash-draken.isportsystem.cz/
    weight: 100
  - identifier: radost-na-drakenu
    name: Radost na Drakenu
    parent: aktivity
    url: http://radost-na-drakenu.webnode.cz/
    weight: 400
params:
  sidebar: left
