---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  fotogalerie:
    default_front_matter_template: fotogalerie
upload_dir: static/images/content
public_path: "/images/content"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:_:filename:"
version: 0.38.1
